### ISSUE TITLE
海报翻译

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#101]
## 贡献理由

帮助社区推广

## 预计完成时间

2021 年 12 月 5 日 —— 2021 年 12月 5 日

## 工作量及积分分配

verenawu0923-100%

![image](https://user-images.githubusercontent.com/91175742/144743416-8bac89fc-6347-4dff-ab83-72114b1a04da.png)

@Whisker17

**Comment by VerenaWu0923** [comment]
https://drive.google.com/file/d/1Yn30IeGGuyW_OfTt7Xqsam_7rfqZXhIJ/view?usp=sharing

**Comment by Whisker17** [comment]
积分 50
