### ISSUE TITLE
自主文章翻译1

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#103]
## 贡献理由

自主文章翻译

## 工作量及积分分配

- bigboyshawty #91 50%
- maixiaoyu123 #90  50%

## 源文件链接   https://en.wikipedia.org/wiki/Prediction_market

源文件链接：
[市场预测.md](https://github.com/zeitgeistpm/Seer-For-China/files/7696658/default.md)

@Whisker17

**Comment by Whisker17** [comment]
积分 60

**Comment by Whisker17** [comment]
![image](https://user-images.githubusercontent.com/12571049/145741298-bfb82ae5-af59-4b54-8e47-6314ba4961c4.png)

**Comment by Whisker17** [comment]
请不要使用google翻译
