### ISSUE TITLE
Kusama Crowdloan 活动的个人推广 ，新增在bifrost参与众贷推广

### ISSUE THREAD

**Issue by airzhangforce** [zeitgeistpm/Seer-For-China#112]
## 贡献理由

Kusama Crowdloan 活动的个人推广，新增在bifrost参与众贷，扩大宣传

2021 年 12 月 11

## 工作量及积分分配

-airzhang 100%

源文件链接：一个内容推广到2个社交媒体
https://app.subsocial.network/5708/ksm-zeitgeist-crowdloan-26702
https://twitter.com/maimaizhang/status/1467840014818344960

@Whisker17

**Comment by Whisker17** [comment]
Subsocial：20
Twitter：10
