### ISSUE TITLE
做了3个meme 图片，用作ksm平行链众筹推广

### ISSUE THREAD

**Issue by airzhangforce** [zeitgeistpm/Seer-For-China#113]
## 贡献理由

做了3个meme 图片，用作ksm平行链众筹推广

## 工作量及积分分配

- airzhang

源文件链接：
https://drive.google.com/drive/folders/18vixIGPKHFxEpKS0umEBlrUzuZXDB8b3?usp=sharing
也发在推特了 https://twitter.com/maimaizhang/status/1467846113617416192

@Whisker17

**Comment by Whisker17** [comment]
积分 30
