### ISSUE TITLE
AMA 翻译

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#114]
## 贡献理由

翻译AMA帮助社区了解项目进展

## 预计完成时间

2021 年 12 月 7日 —— 2021 年 12 月 7 日

## 工作量及积分分配

verenawu0923-100%

@Whisker17

**Comment by VerenaWu0923** [comment]
https://docs.google.com/document/d/1Dn3zJUX3tmvv8-s1UC3Im3FU97QpUgtBBpw5vIjE4CI/edit?usp=sharing

**Comment by Whisker17** [comment]
积分 50
