### ISSUE TITLE
圣诞活动翻译

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#117]
## 贡献理由
翻译圣诞活动

## 预计完成时间

2021 年 12 月 13 日 —— 2021 年 12 月 15 日

## 工作量及积分分配

- verenawu0923 60%
-7uppp 40%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：[xx（需要有超链接）](https://medium.com/zeitgeistseer/announcing-the-zeitgeist-of-christmas-event-cc7f49b28d08)
共计字数：xx

@Whisker17

**Comment by VerenaWu0923** [comment]
https://docs.google.com/document/d/1W7lR6i0W3W62v-MGKqZqv3YOeG7PxQbgtvsirrZtecg/edit?usp=sharing

**Comment by Whisker17** [comment]
积分 40
