### ISSUE TITLE
meme制作

### ISSUE THREAD

**Issue by airzhangforce** [zeitgeistpm/Seer-For-China#118]
## 贡献理由

推广使用

## 预计完成时间

2021 年 12月13号

## 工作量及积分分配

airzhang #11

源文件链接：xx（需要有超链接）

https://drive.google.com/drive/folders/1Zm8DywbC98e-mo6L3HryF7pgXv6CcUIe?usp=sharing
https://twitter.com/maimaizhang/status/1470404622439546884

@Whisker17

**Comment by Whisker17** [comment]
积分 30
