### ISSUE TITLE
Meme制作

### ISSUE THREAD

**Issue by fun2439** [zeitgeistpm/Seer-For-China#127]
## 贡献理由

为什么要申请这项贡献，这对项目发展与推广的好处。

## 预计完成时间

2021 年 12 月 16 日 —— 2021 年 12月 16
![20211216_104424_mh1639622810815](https://user-images.githubusercontent.com/83759778/146298850-66395cc6-9869-4ee9-8843-224e7c41c7ca.jpg)
![IMG_2075_mh1639621814021](https://user-images.githubusercontent.com/83759778/146298856-dbeec46e-ad48-4ceb-9277-fc278827de2f.jpg)
![Concave_Meme_mh1637981449269](https://user-images.githubusercontent.com/83759778/146298860-09f8e2b5-59d9-4edd-bb1d-156b60d8cf76.jpg)
![IMG_2075_mh1637981037801](https://user-images.githubusercontent.com/83759778/146298865-f0678934-685f-4f42-be64-27176e88f3cf.jpg)
![Uploading Screenshot_20211123_163334_com.twitter.android_mh1637656571840.jpg…]()
 日

## 工作量及积分分配

- xx 60%
- yy 40%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：xx（需要有超链接）
共计字数：xx

@Whisker17

**Comment by fun2439** [comment]
![Uploading Screenshot_20211123_163334_com.twitter.android_mh1637656571840.jpg…]()

**Comment by Whisker17** [comment]
积分 40
