### ISSUE TITLE
圣诞活动推广小文章

### ISSUE THREAD

**Issue by airzhangforce** [zeitgeistpm/Seer-For-China#128]
## 贡献理由

圣诞活动推广小文章，扩大传播度

## 预计完成时间

2021年12月16号

## 工作量及积分分配
airzhang #11 100%

源文件链接：xx（需要有超链接）
https://app.subsocial.network/5708/zeitgeist-rmrk-nft-27751
https://twitter.com/maimaizhang/status/1471469806973243392

@Whisker17

**Comment by Whisker17** [comment]
积分 10

**Comment by Whisker17** [comment]
如果可以扩大你的账号的影响力的话，积分会更高
