### ISSUE TITLE
圣诞系列想法延伸

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#131]
## 贡献理由

帮助团队吸引更多ZTG爱好者

## 预计完成时间

2021.12.17
## 工作量及积分分配

bigboyshawty #91 100%
## 源文件链接（如果不是翻译任务，请删除）

源文件链接：xx（需要有超链接）
共计字数：xx
 圣诞周边服饰 圣诞系列和普通系列福袋 以及一个特殊discord抽奖福袋 看到我们的圣诞系列突然产生的奇思妙想 希望团队喜欢 p图能力有限。。做了最大的努力 谢谢

![f8c4b8ddbdcbdb364de37a52396dabb](https://user-images.githubusercontent.com/95017804/146557130-372da6e8-6c76-451f-a372-cff5bc1f1a19.jpg)
![56848eb04302a60b4c39d5ca6509c20](https://user-images.githubusercontent.com/95017804/146557149-aed86480-d0cf-4d6b-b641-ab96b581f137.jpg)
![1d55a868d64beef0d75d8edb678f079](https://user-images.githubusercontent.com/95017804/146557162-b7cb0a69-2871-4a6e-8915-332ba7f3251f.jpg)
![dd7ad8f74d8d8c72c7abff9d65a8e6f](https://user-images.githubusercontent.com/95017804/146557170-6679d971-7a07-432b-8200-175a74f89157.jpg)
![aad1a9f7b56a0385c7d37624535ff7f](https://user-images.githubusercontent.com/95017804/146557180-fe32c41e-f07a-4bc0-86c2-b91b53eb24e8.jpg)

@Whisker17

**Comment by Whisker17** [comment]
积分 10
