### ISSUE TITLE
meme表情

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#140]
## 贡献理由

贡献给项目

## 预计完成时间

2021 年 12.7-12.31

## 工作量及积分分配

- bigboyshawty #91 
## 源文件链接（如果不是翻译任务，请删除）
https://drive.google.com/drive/folders/1DRGptWeGOtMwS5QneZAMd5uy4jrUMZne?usp=sharing

源文件链接：之前第一周完成了3个 这次是剩下3周的全部 谢谢
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
积分 90
