### ISSUE TITLE
12月表情包制作

### ISSUE THREAD

**Issue by shelly0606** [zeitgeistpm/Seer-For-China#146]
## 贡献理由

丰富社区文化
## 预计完成时间

2021 年12月30日

## 工作量及积分分配

shelly100%

## 源文件链接（如果不是翻译任务，请删除）

https://drive.google.com/drive/folders/1IY8A04wnASeb8twwBwA-bmsC64BwA_0a?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 120
