### ISSUE TITLE
12月meme制作（12个）

### ISSUE THREAD

**Issue by zwl123123** [zeitgeistpm/Seer-For-China#147]
## 贡献理由

丰富社区meme文化

## 预计完成时间

2021/12/30

## 工作量及积分分配

zwl123123 100%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://drive.google.com/drive/folders/16DHh4XCWx4zNCfoOoYSyYhO4eUx1tguu?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 120
