### ISSUE TITLE
12月表情

### ISSUE THREAD

**Issue by bluboyno1** [zeitgeistpm/Seer-For-China#149]
## 贡献理由
推广项目

## 预计完成时间
2021.12

## 源文件链接（如果不是翻译任务，请删除）
https://drive.google.com/drive/folders/1iMnjftOFZGGwq-tthRX9OOC1RwWynMqN?usp=sharing

源文件链接：xx（需要有超链接）
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
积分 120
