### ISSUE TITLE
自主贡献2021.12表情包

### ISSUE THREAD

**Issue by migosinthebuilding** [zeitgeistpm/Seer-For-China#150]
## 贡献理由

帮助发展

## 预计完成时间

2021 年 12月

## 工作量及积分分配

- xx 60%
- yy 40%

## 源文件链接（如果不是翻译任务，请删除）
https://drive.google.com/drive/folders/1uuIVVq_3h-800FEM2eXnfVIpECF2rwNK?usp=sharing

源文件链接：xx（需要有超链接）
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
积分 120
