### ISSUE TITLE
表情包

### ISSUE THREAD

**Issue by zhaixing724** [zeitgeistpm/Seer-For-China#151]
## 贡献理由

表情包制作，12月份。

## 预计完成时间

2021 年 12 月 31 日

## 工作量及积分分配

- zhaixing724 100%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：
https://drive.google.com/drive/folders/1xQauAp3qtQOSSf4dhDrml_4LoLstPB14?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 120
