### ISSUE TITLE
12月表情包

### ISSUE THREAD

**Issue by Achilise** [zeitgeistpm/Seer-For-China#152]
## 贡献理由

丰富社区文化

## 预计完成时间

2021 年 12 月 31 日 

## 工作量及积分分配

- xx 60%
- yy 40%

## 源文件链接（如果不是翻译任务，请删除）

https://drive.google.com/drive/folders/1rd91t4sCS9WW59YAgqS74xmIuM1HVjZC?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 120
