### ISSUE TITLE
meme

### ISSUE THREAD

**Issue by zjj104** [zeitgeistpm/Seer-For-China#153]
## 贡献理由

为什么要申请这项贡献，这对项目发展与推广的好处。

## 预计完成时间

2021 年 12 月 31 日

## 工作量及积分分配

- zjj104 100%

## 源文件链接

源文件链接：
https://drive.google.com/drive/folders/1GEkWAAMm1N9XtTPVsTqE3qt9B88TXZjt?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 120
