### ISSUE TITLE
翻译+制图

### ISSUE THREAD

**Issue by zhaixing724** [zeitgeistpm/Seer-For-China#159]
## 贡献理由

让中国朋友了解更多Zeitgeist、futarchy、预测市场知识。

## 预计完成时间

2022 年 2 月 28 日

## 工作量及积分分配

- zhaixing724 100%

## 源文件链接（如果不是翻译任务，请删除）

原文件链接：https://medium.com/zeitgeistseer/prediction-markets-for-dummies-8443e6c22194
共计字数：xx

![1_GZiNcwtFOcX4OQCmUeAgYQ](https://user-images.githubusercontent.com/91657909/155965349-fa6e17fc-b61d-4a0f-974f-0f5a69f5f131.png)
![1_L6El9QiKlYdrDruqZQYLDg](https://user-images.githubusercontent.com/91657909/155965363-a169f742-4a62-44aa-8080-b009fecb0064.png)
![1_1O4JlB5ap-895QTtI8DdyQ](https://user-images.githubusercontent.com/91657909/155965370-4dd31692-c525-4a66-a984-2146b60ceff7.png)
![1_J9jQ4GrKO74-9MZ3QxxUFQ](https://user-images.githubusercontent.com/91657909/155965378-128742d1-4555-4f67-9eb7-dde115343c42.png)
![1_HYrJwBqJ7eu2aKpenDrflg](https://user-images.githubusercontent.com/91657909/155965390-2bd97c6f-aa62-427f-b739-7cbdbde1ecc7.png)
![1_GB5GnM_lNp-_NMQipsNG7g](https://user-images.githubusercontent.com/91657909/155965399-ff59f0c0-758f-4953-891b-2fd5dc966d24.png)
![1_jwHtbrGmBSUqe3ALC8bW6Q](https://user-images.githubusercontent.com/91657909/155965415-c0d27dc5-4c7f-4675-a0e7-8140e850601d.png)

@Whisker17

**Comment by Whisker17** [comment]
不好意思，这个翻译已经有了
