### ISSUE TITLE
表情包1

### ISSUE THREAD

**Issue by xiongmao90** [zeitgeistpm/Seer-For-China#21]
## 贡献理由

加油

## 预计完成时间

2021 年 9 月 1 日

## 工作量及积分分配

xiognmao90-100%
![1](https://user-images.githubusercontent.com/77757386/131630869-9afb110d-559e-4623-aac1-e3a7214eea16.jpg)

@Whisker17

**Comment by Whisker17** [comment]
价值：10 积分
