### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by Arthur1994930** [zeitgeistpm/Seer-For-China#22]
## 贡献理由

翻译文章

## 预计完成时间

2021 年 9 月 7 日 —— 2021 年 9 月 15 日

## 工作量及积分分配

- cyberdoor 100%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://zeitgeist-seer.com/report
共计字数：未知

@Whisker17

**Comment by Whisker17** [comment]
这个的翻译可以查看官方任务0002，是一个系列的，可以申请。
然后分配的话，你可以找到官方管理员让他帮你review，给个分成就行了，这里要注明。
https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/002_Seer_Page_Translation.md

**Comment by Whisker17** [comment]
目前这个申请暂时不通过
