### ISSUE TITLE
事件翻译

### ISSUE THREAD

**Issue by Tanniks** [zeitgeistpm/Seer-For-China#27]
## 贡献理由
Seer 官网作为 Zeitgeist 的大使计划主要信息网站，其官方语言为英语，为了让中文社区的伙伴们更精准更方便的理解 Seer 计划，帮助中文社区成员快速、准确了解到 Seer 社区的最新活动时间，从而更好的参与进来，故将针对 Seer 活动最新事件进行中文翻译。

## 预计完成时间

2021 年 9 月 11 日 —— 2021 年 9 月 18 日

## 工作量及积分分配

- Tanniks 60%
- zjj104 40%

## 源文件链接（如果不是翻译任务，请删除）
任务目标：
- [Seer 事件翻译01](https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/006_Seer_Event01_Translation.md)
- [Seer 事件翻译02](https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/007_Seer_Event02_Translation.md)
- [Seer 事件翻译03](https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/008_Seer_Event03_Translation.md)

源文件链接：
- [Google Drive](https://drive.google.com/drive/folders/18TB4M9j89iIVtJprcCHNzGz0x0toq226?usp=sharing)
- [Github](https://github.com/zjj104/Zeitgeist-Seer/tree/main/Zeitgeist-Event(006-008))
共计字数：1913

@Whisker17

**Comment by Whisker17** [comment]
事件01：50积分
事件02：50积分
事件03：70积分

**Comment by Whisker17** [comment]
合作人请注明 @Tanniks

**Comment by zjj104** [comment]
事件任务已翻译完成，另外更新了002任务的链接。 @Whisker17

**Comment by Whisker17** [comment]
已提PR，请review。
@zjj104 @Tanniks

**Comment by Whisker17** [comment]
质量速度都不错，奖励 30 积分，总积分 50+50+70+30 = 200 
@Tanniks @zjj104
