### ISSUE TITLE
Seer 报告翻译02

### ISSUE THREAD

**Issue by zjj104** [zeitgeistpm/Seer-For-China#30]
## 贡献理由

Seer 官网作为 Zeitgeist 的大使计划主要信息网站，其官方语言为英语，为了让中文社区的伙伴们更精准更方便的理解 Seer 计划，我们希望有能力的社区成员可以对 Seer 官方提供精准的中文翻译，帮助中文社区成员从申请流程，专业术语，任务规则及晋升流程等方面了解 Seer 项目，从而更好的参与进来。

## 预计完成时间

2021 年 9 月 13 日 —— 2021 年 9 月 20 日

## 工作量及积分分配

- zjj104 &nbsp;&nbsp;（翻译）   60%
- Tanniks （校对）40%

## 源文件链接  
- 任务目标：[005](https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/005_Seer_Report02_Translation.md)
源文件链接：
- [Googlle Drive](https://drive.google.com/drive/folders/1DfHJn9cZT3G0h9lfZy6mrngYsQMmwfhN?usp=sharing)
- [Github](https://github.com/zjj104/Zeitgeist-Seer/tree/master/Zeitgeist-Report(005))
共计字数：398

@Whisker17

**Comment by Whisker17** [comment]
积分 50

**Comment by zjj104** [comment]
translate && review。请官方 review。 @Whisker17

**Comment by Whisker17** [comment]
已提交PR @zjj104 @Tanniks

**Comment by zjj104** [comment]
merge review 005 done @Whisker17

**Comment by Whisker17** [comment]
总得分 50+10 = 60
