### ISSUE TITLE
Seer 报告翻译01

### ISSUE THREAD

**Issue by zjj104** [zeitgeistpm/Seer-For-China#31]
## 贡献理由

Seer 官网作为 Zeitgeist 的大使计划主要信息网站，其官方语言为英语，为了让中文社区的伙伴们更精准更方便的理解 Seer 计划，我们希望有能力的社区成员可以对 Seer 官方提供精准的中文翻译，帮助中文社区成员从申请流程，专业术语，任务规则及晋升流程等方面了解 Seer 项目，从而更好的参与进来。

## 预计完成时间

2021 年 9 月 16 日 —— 2021 年 9 月 23 日

## 工作量及积分分配

- zjj104 60%
- Tanniks 40%

## 源文件链接
任务目标：[004](https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/004_Seer_Report01_Translation.md)
源文件链接：
- [Github](https://github.com/zjj104/Zeitgeist-Seer/tree/master/Zeitgeist-Report(004))
- [Google Drive](https://drive.google.com/drive/folders/1DfHJn9cZT3G0h9lfZy6mrngYsQMmwfhN?usp=sharing)
共计字数：1420

@Whisker17

**Comment by Whisker17** [comment]
积分 80

**Comment by zjj104** [comment]
翻译好啦！
ps：report01内容真的很多，是report02的3倍+。
@Whisker17

**Comment by Whisker17** [comment]
由于翻译工作是有上限的，所以只能给一些时间和准确率上的奖励
最终积分：80+20 = 100

**Comment by zjj104** [comment]
merge done.
感谢@Whisker17 的review，每天都是凌晨才review，看得出社区的工作真的很忙并且很有责任感。

**Comment by Whisker17** [comment]
感谢一直以来的贡献，希望之后也可以继续支持我们社区
