### ISSUE TITLE
翻译制图

### ISSUE THREAD

**Issue by xuxinxu** [zeitgeistpm/Seer-For-China#33]
## 贡献理由

为ZTG在国内发展打下基础
## 预计完成时间

2021 年 9 月 22日 —— 2021 年 9 月 23日

## 工作量及积分分配

- 徐鑫 60%
- 7up 40%

## 源文件

![image](https://user-images.githubusercontent.com/12571049/134274421-f7f6baa0-042d-4f22-b4ae-0db10c90998b.png)

@Whisker17

**Comment by xuxinxu** [comment]
![b7526b53c5346e0c0e0282f6286dc63](https://user-images.githubusercontent.com/90595032/134342508-07093bba-28cb-4a5d-9368-581b93511419.png)

**Comment by Whisker17** [comment]
基础积分 70 ，速度质量较好奖励 10 积分，最终 80 积分
