### ISSUE TITLE
Relychain 视频字幕添加 (共9个视频)

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#35]
## 贡献理由

添加中文字幕帮助中国社区成员了解更多资讯

## 预计完成时间

2021 年 9月 22 日 —— 2021 年 9月 25 日

## 工作量及积分分配

VerenaWu0923 70%
7up                    30%

## 源文件链接

https://www.youtube.com/playlist?list=PLdOlgpqyU8ROTFcTLwHtIcRK1HsijJYlS

@Whisker17

**Comment by Whisker17** [comment]
需要合作互相审核，可以选择与管理员进行合作，然后分配积分比例

**Comment by Whisker17** [comment]
一共有八个视频，总时长10分钟左右，积分 150

**Comment by VerenaWu0923** [comment]
添加字幕后视频 :https://drive.google.com/drive/folders/1qdCHMOc_OwBCF8s85yvZwce4uT2y5mca?usp=sharing

**Comment by Whisker17** [comment]
介于质量和速度上佳，最终得分为 150+30 = 180
