### ISSUE TITLE
How Zeitgeist Implements Futarchy 视频字幕添加

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#36]
## 贡献理由

添加中文字幕帮助社区了解更多资讯

## 预计完成时间

2021 年 9 月 22日 —— 2021 年 9月 25日

## 工作量及积分分配

VerenaWu0923 70%
7up                    30%

## 源文件链接

https://www.youtube.com/watch?v=4FQdBqBJN00&ab_channel=ZeitgeistPM

@Whisker17

**Comment by Whisker17** [comment]
需要合作进行

**Comment by Whisker17** [comment]
积分 100

**Comment by VerenaWu0923** [comment]
添加字幕后视频 https://drive.google.com/drive/folders/1aH0AfG8M0s21mKubo_QM5tB3ufHI67lv?usp=sharing

**Comment by Whisker17** [comment]
最终得分为 100+20 = 120
