### ISSUE TITLE
How_To_Mint

### ISSUE THREAD

**Issue by zjj104** [zeitgeistpm/Seer-For-China#38]
## 贡献理由

帮助中文社区了解如何在 single.RMRK 上铸造自己的NFT。

## 预计完成时间

2021 年 9 月 26 日 —— 2021 年 10 月 2 日

## 工作量及积分分配

- zjj104 60%
- Tanniks 40%

## 源文件链接
任务目标：[009](https://github.com/zeitgeistpm/Seer-For-China/blob/main/bounty/official/missions/cn/009_How_To_Mint.md)
源文件链接：
- [Github](https://github.com/zjj104/Zeitgeist-Seer/tree/master/Zeitgeist-NFT(009))
- [Google Drive](https://drive.google.com/drive/folders/1aB7gvPeOd0H0EM5qsVIHxNdw3j5NJBkJ?usp=sharing)
共计字数：630

@Whisker17

**Comment by Whisker17** [comment]
图片较多，文字不太多，价值60积分
