### ISSUE TITLE
airzhang的meme制作#1

### ISSUE THREAD

**Issue by airzhangforce** [zeitgeistpm/Seer-For-China#54]
贡献理由

新人首次参与，努力丰富生态文化

完成时间

2021 年 11月07号

工作量及积分分配

airzhang 100%

源文件链接
https://drive.google.com/drive/folders/19PiE2MWyl3HUSBiumV9vnr57hiN8Au0T

@Whisker17

**Comment by Whisker17** [comment]
积分30
