### ISSUE TITLE
表情包制作

### ISSUE THREAD

**Issue by shelly0606** [zeitgeistpm/Seer-For-China#55]
## 贡献理由

丰富项目生态文化

## 预计完成时间

2021 年 11月7日

## 工作量及积分分配

shelly  100%

源文件链接：https://drive.google.com/drive/folders/1IY8A04wnASeb8twwBwA-bmsC64BwA_0a?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 30
