### ISSUE TITLE
meme制作

### ISSUE THREAD

**Issue by maixiaoyu123** [zeitgeistpm/Seer-For-China#56]
## 贡献理由

为什么要申请这项贡献，这对项目发展与推广的好处。
丰富社区文化，为社区发展做贡献
## 预计完成时间

2021 年 8 月 3 日 —— 2021 年 8 月 7 日

## 工作量及积分分配

- 100%

## 源文件链接（如果不是翻译任务，请删除）
https://drive.google.com/drive/folders/1gZ-4H1o0viYBniD3vSTzV25briMncowN?usp=sharing
源文件链接：xx（需要有超链接）
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
google drive开一下权限吧，我看不到。或者你直接把表情包复制到这里也是可以的

**Comment by maixiaoyu123** [comment]
https://drive.google.com/drive/folders/1gZ-4H1o0viYBniD3vSTzV25briMncowN?usp=sharing
打开了

**Comment by Whisker17** [comment]
积分 30

**Comment by Whisker17** [comment]
好像没有看到你的DB，麻烦创建一下

**Comment by maixiaoyu123** [comment]
好了
