### ISSUE TITLE
表情包

### ISSUE THREAD

**Issue by meloveme9959** [zeitgeistpm/Seer-For-China#61]
## 贡献理由
贡献目的：获得ZTG
贡献影响：提供表情包
## 预计完成时间

2021 年 11月9号

## 工作量及积分分配
meloveme    100％

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://drive.google.com/drive/folders/155t5nSno2RZsTmq84KB-8UB6BMBoGwnn?usp=sharing  （需要有超链接）

**Comment by Whisker17** [comment]
你这链接不对。。

**Comment by meloveme9959** [comment]
> 你这链接不对。。

刚改过了，麻烦再审核下吧~

**Comment by Whisker17** [comment]
权限没开。。

**Comment by Whisker17** [comment]
积分 20

**Comment by meloveme9959** [comment]
> 积请问之后更新是继续在这里更新，还是新建issue

**Comment by meloveme9959** [comment]
> 积分 20

请问之后是在这里继续更新，还是需要新建issue？

**Comment by Whisker17** [comment]
新建
