### ISSUE TITLE
ZTG经济模型-翻译

### ISSUE THREAD

**Issue by Tanniks** [zeitgeistpm/Seer-For-China#63]
## 贡献理由

更新ZTG代笔经济模型。

## 预计完成时间

2021 年 11 月 14 日 —— 2021 年 11 月 15 日

## 工作量及积分分配

- Tanniks 60%
- zjj104 40%

## 源文件链接
源文件链接：https://zeitgeist.pm/ztg
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
积分 60

**Comment by Tanniks** [comment]
[翻译链接](https://github.com/zjj104/Zeitgeist-Seer/blob/master/Zeitgeist-token/token-Economy.md)

**Comment by Whisker17** [comment]
没什么问题，积分 60+10（速度奖励） = 70
