### ISSUE TITLE
meme制作

### ISSUE THREAD

**Issue by zwl123123** [zeitgeistpm/Seer-For-China#66]
## 贡献理由

丰富社区文化

## 预计完成时间

2021/11/16

## 工作量及积分分配

zwl123123 100%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://drive.google.com/drive/folders/1QjgSjLSrxz_kUDdcO4Yi0fCOOeh054fi?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 30
