### ISSUE TITLE
wallpaper

### ISSUE THREAD

**Issue by zjj104** [zeitgeistpm/Seer-For-China#67]
## 贡献理由
丰富社区文化。

## 预计完成时间

2021 年 11 月 18 日

## 工作量及积分分配

- zjj104 100%

源文件链接：[wallpaper](https://drive.google.com/drive/folders/15s1WzGBmkEVa8i1vlXsz0_EUCih0uhe7)

@Whisker17

**Comment by Whisker17** [comment]
做得很好，积分 20 + 20（奖励）= 40
