### ISSUE TITLE
wallpaper_add

### ISSUE THREAD

**Issue by zjj104** [zeitgeistpm/Seer-For-China#71]
## 贡献理由

丰富社区生态。

## 预计完成时间

2021 年 11 月 22 日

## 工作量及积分分配

- zjj104 100%

## 源文件链接

源文件链接：[wallpaper](https://drive.google.com/drive/folders/15s1WzGBmkEVa8i1vlXsz0_EUCih0uhe7?usp=sharing)

@Whisker17

**Comment by zjj104** [comment]
add wallpaper3 && wallpaper4

**Comment by Whisker17** [comment]
积分 20 + 30（奖励）= 50

**Comment by Whisker17** [comment]
提个建议，可以把分辨率弄得高一点嘛，这个分辨率不太适合做壁纸了
