### ISSUE TITLE
meme制作

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#73]
## 贡献理由

为了让更多人关注到这个项目 以及用有趣的方式吸引对方

## 预计完成时间

2021 年 11.25 
## 工作量及积分分配

- bigboyshawty100%

源文件链接（如果不是翻译任务，请删除）
源文件链接：https://drive.google.com/drive/folders/1pZaboR65kRY_Sp5z_oyT2mOTjCBShrIx?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 30
