### ISSUE TITLE
翻译文章

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#74]
## 贡献理由

推广我们的项目 让更多人了解并参与其中

## 预计完成时间

2021 年 11.25
## 工作量及积分分配

[Subsquid会帮助Zeitgeist准备未来的活动.md](https://github.com/zeitgeistpm/Seer-For-China/files/7601811/Subsquid.Zeitgeist.md)
-bigboyshawty 50%
- XiaoSanMu 50%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：(https://twitter.com/polkadotnews/status/1463076109470289921)

@Whisker17

**Comment by Whisker17** [comment]
这个合作文案我们已经有中文版了

**Comment by Whisker17** [comment]
可以去看一下Medium上面的文章

**Comment by Whisker17** [comment]
然后流程的话，先把你要翻译的东西建个Issue告诉我们，我们通过了之后再开始翻译，不然容易做无用功
