### ISSUE TITLE
文章翻译

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#76]
## 贡献理由

让更多人了解我们的项目 

## 预计完成时间

2021 年 11.26-11.30

## 工作量及积分分配

-bigboyshatwy 50%
- xiaosanmu 50%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：(https://medium.com/zeitgeistseer/zeitgeist-seer-program-a9858894f409)
共计字数：

@Whisker17

**Comment by Whisker17** [comment]
这篇已经翻译过了，另外麻烦添加一下自己的DB
