### ISSUE TITLE
文章翻译

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#77]
## 贡献理由

翻译成中文帮助中文社区

## 预计完成时间

2021 年 11 月 26 日 —— 2021 年 11月 28日

## 工作量及积分分配

- verenawu0923 80%
- 7up 20%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://blog.zeitgeist.pm/is-democracy-the-best-we-can-do-for-the-metaverse/
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
积分 60

**Comment by VerenaWu0923** [comment]
https://docs.google.com/document/d/1xsMaJGdw_mA0D8lGono_e69HpC5Z7ZjhKKipw4-vqL4/edit#
