### ISSUE TITLE
Meme制作

### ISSUE THREAD

**Issue by fun2439** [zeitgeistpm/Seer-For-China#79]
## 贡献理由

为什么要申请这项贡献，这对项目发展与推广的好处。

## 预计完成时间

2021 年 11月 17日 —— 2021 年 11 月 27日

## 工作量及积分分配

- xx 60%
- yy 40%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://drive.google.com/folderview?id=1-0LGxmx45Sx8_cpp1DSAZwSH9sZernDs
共计字数：

@Whisker17

**Comment by Whisker17** [comment]
权限设置一下，我没法看

**Comment by fun2439** [comment]
> 权限设置一下，我没法看

可以了
