### ISSUE TITLE
文章翻译(修改）

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#80]
## 贡献理由

让大家更好的了解什么是市场预测

## 预计完成时间

2021 年 11.27-11.30

## 工作量及积分分配

- bigboyshaty50%
-xiaosanmu 50%

## 源文件链接（如果不是翻译任务，请删除）
https://medium.com/zeitgeistseer/zeitgeist-the-new-era-of-prediction-markets-98311a50c6ef
https://medium.com/zeitgeistseer/how-to-get-titles-in-zeitgeist-seer-program-fd9c7b7263a9
源文件链接：
共计字数：

[预测市场-它们是什么？.md](https://github.com/zeitgeistpm/Seer-For-China/files/7616315/-.md)

@Whisker17
[怎样在Zeitgeist Seer Program里获得头衔.md](https://github.com/zeitgeistpm/Seer-For-China/files/7616656/Zeitgeist.Seer.Program.md)

**Comment by Whisker17** [comment]
你可能对预测市场这块理解有些偏差了，我看了一下好像关联度不是很高

**Comment by Whisker17** [comment]
你这几篇已经有翻译了

**Comment by Whisker17** [comment]
第一篇 50
第二篇 40

**Comment by Whisker17** [comment]
@Tanniks

**Comment by Tanniks** [comment]
我可以提一点意见吗？
首先，翻译的格式尽量遵循 markdown 规范，[这儿](https://docs.github.com/cn/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)有一些 Markdown 的基本格式或许会对你有所帮助。
另外，建议 @xiaosanmu 认真做一下校对，部分语句不太通顺，我同步的时候阅读会有些困难，例如：
```
- 原文：Unfortunately, I couldn’t speak due to the microphone issues, that is why I have decided to tell more about myself and wrote Bob.
- 你的译文：不幸的是，由于麦克风的问题，我不能说话，这就是为什么我决定告诉更多关于我自己和写bob
- 修改译文：不幸的是，由于麦克风问题我无法说话，这就是为什么我决定更多地介绍自己并写信给Bob。
```
@bigboyshawty

**Comment by Tanniks** [comment]
[第一篇](https://medium.com/zeitgeistseer/%E9%A2%84%E6%B5%8B%E5%B8%82%E5%9C%BA-%E5%AE%83%E4%BB%AC%E6%98%AF%E4%BB%80%E4%B9%88-24c0eae722e8)
[第二篇](https://medium.com/zeitgeistseer/%E6%80%8E%E6%A0%B7%E5%9C%A8zeitgeist-seer-program%E9%87%8C%E8%8E%B7%E5%BE%97%E7%A7%B0%E5%8F%B7-d10ce0a189ea)
@Whisker17

**Comment by bigboyshawty** [comment]
> 我可以提一点意见吗？ 首先，翻译的格式尽量遵循 markdown 规范，[这儿](https://docs.github.com/cn/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)有一些 Markdown 的基本格式或许会对你有所帮助。 另外，建议 @xiaosanmu 认真做一下校对，部分语句不太通顺，我同步的时候阅读会有些困难，例如：
> 
> ```
> - 原文：Unfortunately, I couldn’t speak due to the microphone issues, that is why I have decided to tell more about myself and wrote Bob.
> - 你的译文：不幸的是，由于麦克风的问题，我不能说话，这就是为什么我决定告诉更多关于我自己和写bob
> - 修改译文：不幸的是，由于麦克风问题我无法说话，这就是为什么我决定写信给Bob并更多地介绍自己。
> ```
> 
> @bigboyshawty

好的谢谢 我会注意的
