### ISSUE TITLE
视频字幕添加

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#82]
## 贡献理由

字幕添加帮助中国社区了解项目

## 预计完成时间

2021 年 11月 29 日 —— 2021 年 11 月 29 日

## 工作量及积分分配

-verenawu0923 100%

https://www.youtube.com/watch?v=fjL0MXa9CmI&t=801s

@Whisker17

**Comment by VerenaWu0923** [comment]
https://drive.google.com/file/d/1NkPdbWF2OVpW-VnQ34hGyPsl2WJW3afE/view?usp=sharing

**Comment by VerenaWu0923** [comment]
@Whisker17

**Comment by Whisker17** [comment]
积分 100
