### ISSUE TITLE
meme

### ISSUE THREAD

**Issue by Achilise** [zeitgeistpm/Seer-For-China#85]
## 贡献理由

丰富社区文化

## 预计完成时间

2021 年 11 月 30 日 

## 工作量及积分分配

- Achilise 100%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://drive.google.com/drive/folders/1Vof2zu0u97Vh1xyvgTgQ6zG0yO9HTt8S?usp=sharing
共计字数：xx

@Whisker17

**Comment by Whisker17** [comment]
积分 120
