### ISSUE TITLE
meme制作

### ISSUE THREAD

**Issue by maixiaoyu123** [zeitgeistpm/Seer-For-China#86]
## 贡献理由
meme制作

## 预计完成时间

2021 年 11月 30 日 —— 2021 年 11月 30日

## 工作量及积分分配

- 100%

## 源文件链接（如果不是翻译任务，请删除）
https://drive.google.com/drive/folders/1JYoEOWGBgEPXY-OurqnAmgXeCiL5B7oo?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
积分 30
