### ISSUE TITLE
meme制作

### ISSUE THREAD

**Issue by bigboyshawty** [zeitgeistpm/Seer-For-China#93]
## 贡献理由

推广Zeigeist

## 预计完成时间

2021 年 12.1-12.7

## 工作量及积分分配

bigboyshawty 100%

## 源文件链接（如果不是翻译任务，请删除）

源文件链接：https://drive.google.com/drive/folders/1uA0OJJzSqKnf67LPg5cJp-KT23troLLB?usp=sharing

@Whisker17

**Comment by Whisker17** [comment]
权限没开。。

**Comment by bigboyshawty** [comment]
> 权限没开。。

changed

**Comment by Whisker17** [comment]
积分 30
