### ISSUE TITLE
字幕加载

### ISSUE THREAD

**Issue by VerenaWu0923** [zeitgeistpm/Seer-For-China#94]
## 贡献理由

帮助中国社区了解更多

## 预计完成时间

2021 年 12月 3 日 —— 2021 年 12 月 4 日

## 工作量及积分分配

verenawu0923 - 100%
## 源文件链接
https://www.youtube.com/watch?v=SlX0xbzArac&ab_channel=ICONPLUS

@Whisker17

**Comment by VerenaWu0923** [comment]
https://drive.google.com/file/d/1l_UNayeULAXT5sd0RWg9yCCd7ACecPpy/view?usp=sharing  @Whisker17

**Comment by Whisker17** [comment]
积分50
