### ISSUE TITLE
周边设计

### ISSUE THREAD

**Issue by kelly0529** [zeitgeistpm/Seer-For-China#96]
## 贡献理由
希望官方能推出周边

## 预计完成时间

2021 年 12月 3 日 —— 2021 年 12 月 3 日

## 工作量及积分分配

小乖 100%

@Whisker17

**Comment by kelly0529** [comment]
![图片](https://user-images.githubusercontent.com/39582722/144555437-2c4af0c3-4eb7-4880-8e85-e6edb559c4d3.png)

**Comment by Whisker17** [comment]
关于周边我们内部已经有设计了，但是非常感谢你的设计，很棒，我也会给团队推荐你的设计的。

积分 60
