### ISSUE TITLE
Kusama Crowdloan 活动的个人推广

### ISSUE THREAD

**Issue by airzhangforce** [zeitgeistpm/Seer-For-China#98]
## 贡献理由

Kusama Crowdloan 活动的个人推广，扩大宣传

## 预计完成时间

2021 年 12 月 11 

## 工作量及积分分配

airzhang 100%

源文件链接：xx（需要有超链接）
https://app.subsocial.network/5708/zeitgeist-kusama-crowdloan-26625
https://twitter.com/maimaizhang/status/1467360873249665025

@Whisker17

**Comment by Whisker17** [comment]
推 10 
subsocial 30
共计 40
